app:
  adapter:
    type: 'vdv'
    url: 
      de: 'https://yourdomain.dev/alerts/de/[alertId]'
  participants: './config/participants.yaml'
  subscriber: PY_TEST_SUBSCRIBER
  publisher: PY_TEST_PUBLISHER