name: Build Latest
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: docker-login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker-build-push
        run: |
          docker build -t sebastianknopf/vdv736gtfsrt:latest .
          docker push sebastianknopf/vdv736gtfsrt:latest