name: Build Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch: # allow manual start

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: extract-meta-data
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: sebastianknopf/vdv736gtfsrt
      - name: docker-login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker-build-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Important: Allow to modify the repository
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: create-gh-release
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}